import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Sidebar } from '@/components/ui'
import { useState } from 'react'

interface ButtonTab {
  text: string,
  active: boolean
}

export default function Home() {

  const [ buttonTabs, setButtonTabs ] = useState<ButtonTab[]>([
    {
      text: 'My Details',
      active: false
    },
    {
      text: 'Profile',
      active: false
    },
    {
      text: 'Password',
      active: false
    },
    {
      text: 'Team',
      active: false
    },
    {
      text: 'Plan',
      active: false
    },
    {
      text: 'Billing',
      active: true
    },
    {
      text: 'Notifications',
      active: false
    },
    {
      text: 'Integrations',
      active: false
    },
    {
      text: 'API',
      active: false
    },
  ])

  return (
    <>
      <Head>
        <title>Vencru</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main__layout}>
        <aside className={styles.sidebar}>
          <Sidebar />
        </aside>
        <div className={styles.main__content}>
          <header className={styles.main__header}>
            <div>
              <p className={styles.page__heading}>Settings</p>
              <p className={styles.page__subheading}>Manage your team and preferences here.</p>
            </div>
            <div className={styles.button__group}>
              { buttonTabs.map((item, index) => {
                return (
                  <button key={`button-tab-${item.text}`}
                    className={ !item.active ?
                      styles.button__group__item : 
                      styles.button__group__active__item
                    }
                  >{ item.text }</button>
                )
              })}
              {/* <button
                className={styles.button__group__item}
              >Profile</button>
              <button
                className={styles.button__group__item}
              >Password</button>
              <button
                className={styles.button__group__item}
              >Team</button>
              <button
                className={styles.button__group__item}
              >Plan</button>
              <button
                className={styles.button__group__item}
              >Billing</button>
              <button
                className={styles.button__group__item}
              >Notifications</button>
              <button
                className={styles.button__group__item}
              >Integrations</button>
              <button
                className={styles.button__group__item}
              >API</button> */}
            </div>
          </header>
        </div>
      </main>
    </>
  )
}
