import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Divider, Input, Sidebar } from '@/components/ui'
import { useState } from 'react'
import { MailIcon, MastercardIcon, VisaIcon } from '@/components/icons'

interface ButtonTab {
  text: string,
  active: boolean
}

interface Card {
  type: 'Visa' | 'Mastercard',
  last4: string,
  expiry: string
}

export default function Home() {

  const [ buttonTabs, setButtonTabs ] = useState<ButtonTab[]>([
    {
      text: 'My Details',
      active: false
    },
    {
      text: 'Profile',
      active: false
    },
    {
      text: 'Password',
      active: false
    },
    {
      text: 'Team',
      active: false
    },
    {
      text: 'Plan',
      active: false
    },
    {
      text: 'Billing',
      active: true
    },
    {
      text: 'Notifications',
      active: false
    },
    {
      text: 'Integrations',
      active: false
    },
    {
      text: 'API',
      active: false
    },
  ])

  const [ cards, setCards ] = useState<Card[]>([
    {
      type: 'Visa',
      last4: '1234',
      expiry: '06/2024'
    },
    {
      type: 'Mastercard',
      last4: '1234',
      expiry: '06/2024'
    }
  ])

  const [ selectedCard, setSelectedCard ] = useState<number>(0);

  return (
    <>
      <Head>
        <title>Vencru</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main__layout}>
        <aside className={styles.sidebar}>
          <Sidebar />
        </aside>
        <div className={styles.main__content}>
          <header className={styles.main__header}>
            <div>
              <p className={styles.page__heading}>Settings</p>
              <p className={styles.page__subheading}>Manage your team and preferences here.</p>
            </div>
            <div className={styles.button__group}>
              { buttonTabs.map((item, index) => {
                return (
                  <button key={`button-tab-${item.text}`}
                    className={ !item.active ?
                      styles.button__group__item : 
                      styles.button__group__active__item
                    }
                  >{ item.text }</button>
                )
              })}
            </div>
          </header>
          <section>
            <div className={styles.section__header}>
              <p className={styles.section__heading}>Payment Method</p>
              <p className={styles.section__subheading}>Update your billing details and address.</p>
            </div>
            <Divider
              direction={'horizontal'}
            />
            <div className={styles.section__form}>
              <div className={styles.section__form__left}>
                <p className={styles.form__heading}>Contact email</p>
                <p className={styles.form__subheading}>Where should invoices be sent?</p>
              </div>
              <div className={styles.section__form__right}>
                <form className={styles.contact__email__form}>
                  <div className={styles.form__item}>
                    <input 
                      type={'radio'}
                      name='contact-email'
                      id='default-contact-email'
                      className={styles.form__radio__input}
                    />
                    <label 
                      htmlFor='default-contact-email'
                      className={styles.form__item__label}
                    >
                      <p className={styles.form__heading}>Send to my account email</p>
                      <p className={styles.form__subheading}>olivia@untitledui.com</p>
                    </label>
                  </div>
                  <div className={styles.form__item}>
                    <input 
                      type={'radio'}
                      name='contact-email'
                      id='alternate-contact-email'
                      className={styles.form__radio__input}
                    />
                    <label 
                      htmlFor='alternate-contact-email'
                      className={styles.form__item__label}
                    >
                      <p className={styles.form__heading}>Send to an alternative email</p>
                      <Input 
                        placeholder="billing@untitledui.com"
                        icon={<MailIcon />}
                        className={styles.input__container}
                      />
                    </label>
                  </div>
                </form>
              </div>
            </div>
            <Divider 
              direction={'horizontal'}
            />
            <div className={styles.card__section__form}>
              <div className={styles.section__form__left}>
                <p className={styles.form__heading}>Card details</p>
                <p className={styles.form__subheading}>Select default payment method.</p>
              </div>
              <div className={styles.section__form__right}>
                <form className={styles.contact__email__form}>
                  { cards.map((card, index) => {
                    return (
                      <div 
                        className={`${styles.form__item} ${styles.pointer}`}
                        key={`card-${index}`}   
                        onClick={() => setSelectedCard(index)}
                      >
                        <div
                          className={
                            selectedCard === index ? 
                            styles.active__card :
                            styles.card
                          }
                        >
                          { card.type === 'Visa' && <VisaIcon /> }
                          { card.type === 'Mastercard' && <MastercardIcon /> }
                          <div className={styles.card__details}>
                            <div>
                              <p className={styles.card__number}>{ card.type } ending in { card.last4 }</p>
                              <p className={styles.card__exp}>Expiry { card.expiry }</p>
                            </div>
                            <div className={styles.card__actions}>
                              <button
                                className={styles.card__set__as__default}
                              >Set as default</button>
                              <button
                                className={styles.card__edit}
                              >Edit</button>
                            </div>
                          </div>
                          <input 
                            type={'radio'}
                            name='card'
                            id="visa-card"
                            checked={ selectedCard === index }
                            className={styles.card__radio__button}
                          />
                        </div>
                      </div>
                    )
                  })}
                  <div className={styles.form__item}>
                    
                  </div>
                </form>
              </div>
            </div>
          </section>
        </div>
      </main>
    </>
  )
}
